### ISSUE TITLE
Grape examples appear to be incomplete

### ISSUE THREAD

**Issue by kastork** [groovyfx-project/groovyfx#42] opened 2016-05-21 20:18 UTC
When trying to run an example using the suggested @Grab approach.  Receive an exception.

e.g. this is the accordion example copied from the demos directory.  Then, as suggested in README, add the Grab annotation.
```
@Grab('org.groovyfx:groovyfx:8.0.0')

import static groovyx.javafx.GroovyFX.start

start {
    stage(title: "GroovyFX Accordion Demo", x: 100, y: 100, visible: true, style: "decorated", primary: true) {
        scene(fill: GROOVYBLUE, width: 400, height: 400) {
            accordion {
                titledPane(id: "t1", text: "Label 1") {
                    content {
                        label(text: "This is Label 1\n\nAnd there were a few empty lines just there!")
                    }
                }
                titledPane(id: "t2", text: "Label 2") {
                    content {
                        label(text: "This is Label 2\n\nAnd there were a few empty lines just there!")
                    }
                }
                titledPane(id: "t3", text: "Label 3") {
                    // this is content
                    label(text: "This is Label 3\n\nAnd there were a few empty lines just there!")
                }
            }
        }
    }
}
```
Then, using either
`groovy AccordionDemo.groovy`
or
`groovy -cp $JAVA_HOME/jre/lib/ext/jfxrt.jar AccordionDemo.groovy`

results in

```sh
Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at com.sun.proxy.$Proxy4.onClassInfo(Unknown Source)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
	at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
	at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)
	at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
	at javafx.scene.control.Control.<clinit>(Control.java:87)
	... 1 more
```

The google machine suggests this error can be corrected by instantiating a `JFXPanel` by hand, but I'm not sure where you would do this.  I tried it at the root script level:

```
   new JFXPanel()
   start {
      ...
```
and also at the top of the start block with no success.

Also, I've seen people suggest this

`@GrabConfig(systemClassLoader=true, initContextClassLoader=true)`

Also no change

So it seem like  there must be a missing step in those places where you suggest a `@Grape` invocation to pull in groovyfx.

I'd try it with the 9.0 snapshot, but it doesn't seem to resolve.

```sh 
grape resolve org.groovyfx groovyfx 8.0.0
/Users/kirk/.groovy/grapes/org.groovyfx/groovyfx/jars/groovyfx-8.0.0.jar
/Users/kirk/.groovy/grapes/org.codehaus.groovy/groovy-all/jars/groovy-all-2.4.6.jar

grape resolve org.groovyfx groovyfx 9.0.0-SNAPSHOT
Error in resolve:
	Error grabbing Grapes -- [unresolved dependency: org.groovyfx#groovyfx;9.0.0-SNAPSHOT: not found]
Perhaps the grape is not installed?
```

**Comment by russel** [comment] 2016-05-22 09:56
I think we need to separate the JDK8 and JDK9 problems into two. Also we need to be sure which Groovy versions are being used. This script with JDK9 119 gives me the java.lang.ExceptionInInitializerError but the stack is totally different. Can I propose we close this issue and start two new ones?

**Comment by bgoetzmann** [comment] 2016-10-05 11:45
Same thing for me, with a Groovy script using a same Grab annotation.
I'm using Windows 7, and JDK 8 (1.8.0_102).
My stacktrace is slightly different:

```
Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
        at java_lang_Class$isAssignableFrom.call(Unknown Source)
        at com.sun.proxy.$Proxy4.onClassInfo(Unknown Source)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:273)
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:268)
        at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(PlatformImpl.java:550)
        at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(PlatformImpl.java:512)
        at javafx.scene.control.Control.<clinit>(Control.java:87)
        ... 2 more
```

Bertrand

**Comment by bgoetzmann** [comment] 2016-10-06 10:49
If I change `@Grab('org.groovyfx:groovyfx:8.0.0')` by `@Grab('org.codehaus.groovyfx:groovyfx:0.4.0')` (strange idea isn't it?), the JavaFX application starts without exception.

Note: I test it with the example code of the GroovyFX project home page. If the app starts well, I have a white background (instead of black), and the window width seems not correct.

**Comment by russel** [comment] 2016-10-06 12:52
@bgoetzmann If I change to 0.4.0 I just get a:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during conversion: Error grabbing Grapes -- [unresolved dependency: org.groovyfx#groovyfx;0.4.0: not found]
```

**Comment by russel** [comment] 2016-10-06 12:59
With 8.0.0 on JDK9 I get:
```
Caught: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at java_lang_Class$isAssignableFrom$0.call(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at com.sun.proxy.$Proxy6.onClassInfo(Unknown Source)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
	at com.sun.javafx.application.PlatformImpl.runLater(javafx.graphics@9-ea/PlatformImpl.java:396)
	at com.sun.javafx.application.PlatformImpl.runLater(javafx.graphics@9-ea/PlatformImpl.java:391)
	at com.sun.javafx.application.PlatformImpl.setPlatformUserAgentStylesheet(javafx.graphics@9-ea/PlatformImpl.java:673)
	at com.sun.javafx.application.PlatformImpl.setDefaultPlatformUserAgentStylesheet(javafx.graphics@9-ea/PlatformImpl.java:635)
	at javafx.scene.control.Control.<clinit>(javafx.controls@9-ea/Control.java:99)
	... 16 more
```
and with JDK8 I get:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
General error during semantic analysis: java.lang.NoClassDefFoundError: javafx.stage.Stage
```

**Comment by aalmiray** [comment] 2016-10-06 13:01
Ah lovely. Looks like the specific version of Groovy can't parse the new JDK9 version number. That's the problem Russel encounters when running with JDK9. Now on JDK8 we get a toolkit initialization exception (I can confirm the exception). This may be caused by an early access to a JavaFX class in SGB before the toolkit has been properly initialized.

I can have a loom at this issue tonight at the Luzern Hackergarten,

**Comment by russel** [comment] 2016-10-06 13:09
@aalmiray Do you think the parsing is a Groovy or GroovyFX thing?

**Comment by aalmiray** [comment] 2016-10-06 13:15
I was too quick to judge on Groovy directly, the problem is in GroovyFX given the stacktrace

    at groovyx.javafx.JdkUtil.jdkIsBefore8(JdkUtil.groovy:5)

This means we can fix the problem from our side ;-)

**Comment by bgoetzmann** [comment] 2016-10-06 15:52
@russel For the 0.4.0 version test, be careful, the groupId is different! I replaced @Grab('**org.groovyfx:**groovyfx:8.0.0') by @Grab('**org.codehaus.groovyfx:**groovyfx:0.4.0').

**Closed** 2016-10-06 17:27 UTC
Labels: bug

**Comment by russel** [comment] 2016-10-06 17:50
We should publicise the way people can use this artefact prior to it being published formally.

**Comment by jagedn** [comment] 2017-04-02 10:07
Hi @kastork 

I had the same problem (jdk8, grape and Toolkit not initialized) and I was able to solve it using grape API instead of annotation. I think grape load services from MANIFEST before JafaFX to be ready

import groovy.grape.Grape
new javafx.embed.swing.JFXPanel();

Grape.grab(group:'org.groovyfx',module:'groovyfx',version:'8.0.0',transitive:false)
Class.forName('groovyx.javafx.GroovyFX').start {
  stage(title: 'GroovyFX Hello World', visible: true) {
    scene(fill: BLACK, width: 500, height: 250) {
      hbox() {
	text(text: 'Groovy', font: '80pt sanserif') {
		fill linearGradient(endX: 0, stops: [PALEGREEN, SEAGREEN])
	}
	text(text: 'FX', font: '80pt sanserif') {
		fill linearGradient(endX: 0, stops: [CYAN, DODGERBLUE])
		effect dropShadow(color: DODGERBLUE, radius: 25, spread: 0.25)
	}
      }
    }
   }
}

**Comment by mfreeman-xtivia** [comment] 2018-01-28 14:50
Related to the comment from @russel --can someone describe how we can make use of this fix today since it does not appear 8.1 has been published yet?

**Comment by bitsnaps** [comment] 2018-05-12 13:16
@mfreeman-xtivia based on the example of @jagedn, I believe this has something to do with Grape and they it loads dependencies, the best way for now is to use Gradle, this is what works for me:
```
apply plugin: 'groovy'
//project.ext.set('javafxHome', System.env['JAVAFX_HOME'])
repositories {
    jcenter()
}
dependencies {
    compile 'org.groovyfx:groovyfx:8.0.0'
    //compile files("${javafxHome}/rt/lib/jfxrt.jar")
}
task run(type: JavaExec) {
    main = 'HelloGroovyFX'
    classpath sourceSets.main.runtimeClasspath
}
```
Using:
Gradle 3.5.1
Groovy: 2.4.4
JVM: 1.8.0_101
Win7.

**Comment by jagedn** [comment] 2018-05-12 18:26
I "solved" the issue using a launcher who initialized javafx before to run the real script

LaunchFXScript.groovy

```
import javafx.embed.swing.JFXPanel
new JFXPanel()
File f = new File(args[0])
run(f,args.drop(1)) 
```
MyFXScript.groovy
```
@Grab(group='org.groovyfx',module='groovyfx',version='8.0.0',transitive=true, noExceptions=true)
import static groovyx.javafx.GroovyFX.start
start {
    stage(title: 'VisualSheet', height: 600, visible: true) {
        scene(fill: BLACK, width: 800, height: 250) {
            hbox(padding: 60) {
                button( text:'Load')
            }
   }
}
```

so you can run `groovy LaunchFXScript.groovy MyFXScript.groovy` 

but I know it's a trick
